### ISSUE TITLE
Problem with Swaps

### ISSUE THREAD

**Issue by mafiagr** [newstlastlist/GuruShots-auto-Voter#1]
It works, but theres a problem. It is using swaps, obviously when gurushots suggests a change.

**Comment by SandSux** [comment]
Agreed. When Gurushots offers the Swap Suggestion, the autovoter  automagically issues those recommended swaps.

**Comment by mafiagr** [comment]
I installed adblock in Chromium (node_modules\puppeteer\.local-chromium\win64\chrome-win) and set swap button as an advertise, so the Adblock blocks the button. I think it will work!

**Comment by SandSux** [comment]
Good thinking! Let me know how your proposed work-around works out.

**Comment by newstlastlist** [comment]
i will try to fix this problem next week

**Comment by kamikaze** [comment]
> 
> 
> i will try to fix this problem next week

any success?

**Comment by as400** [comment]
Hi, did you find how to fix the swap issue ? I tried without any chance

**Comment by rikrakrak** [comment]
Doesnt work at all

**Comment by mafiagr** [comment]
It stopped working yesterday, now it works! Unfortunately the adblock solution does not solve the problem completely. It reduces for sure the times i had autoswaps but when I join many contests, it autoswaps some times.

**Comment by rikrakrak** [comment]
All i get is timeouterror

**Comment by rikrakrak** [comment]
c:\GuruShots>node gurushitsautolike.js
(node:6380) UnhandledPromiseRejectionWarning: TimeoutError: Navigation timeout of 30000 ms exceeded
    at c:\GuruShots\node_modules\puppeteer\lib\LifecycleWatcher.js:142:21
    at async FrameManager.waitForFrameNavigation (c:\GuruShots\node_modules\puppeteer\lib\FrameManager.js:139:19)
    at async Frame.waitForNavigation (c:\GuruShots\node_modules\puppeteer\lib\FrameManager.js:414:12)
    at async Page.waitForNavigation (c:\GuruShots\node_modules\puppeteer\lib\Page.js:695:12)
    at async main (c:\GuruShots\gurushitsautolike.js:31:4)
  -- ASYNC --
    at Frame.<anonymous> (c:\GuruShots\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.waitForNavigation (c:\GuruShots\node_modules\puppeteer\lib\Page.js:695:49)
    at Page.<anonymous> (c:\GuruShots\node_modules\puppeteer\lib\helper.js:112:23)
    at main (c:\GuruShots\gurushitsautolike.js:31:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:6380) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6380) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by newstlastlist** [comment]
sry, i put some huy on this project, mb later i will fix all of this shit )))

**Comment by kamikaze** [comment]
> 
> 
> sry, i put some huy on this project, mb later i will fix all of this shit )))

don't be a pidr, unveil the code

**Comment by KyryloMyronov** [comment]
I added 

```      
const closeBtns = document.getElementsByClassName('c-cards__close');  
for (var btn of closeBtns) {  
    $(btn).click();  
    await new Promise(resolve => setTimeout(resolve, 1000));  
}
```
So it just will close all the modal buttons(both swaps suggestions and swap results).

**Comment by mjohl** [comment]
**There is a fixed version for the swap issue and it will ignore swap modals:**

This is the condition to ensure the correct button is used, so swaps will be ignored.

         if (btn.parentNode.classList[0] == "c-challenges-item-mobile__exposure__vote") {

**Comment by mjohl** [comment]
@newstlastlist I added a pull request for my fix.
