### ISSUE TITLE
does not work anymore

### ISSUE THREAD

**Issue by noverotajs** [newstlastlist/GuruShots-auto-Voter#7]
cant find login anymore

**Comment by ghost** [comment]
I made a pull request, but check here => https://github.com/mattlenton/GuruShots-auto-Voter/blob/master/GuruShitsAutoLike.js

I did a temp fix, 
Gurushots might change by tomorrow again

**Comment by noverotajs** [comment]
Thank you a lot...

**Comment by xenbaloch** [comment]
> I made a pull request, but check here => https://github.com/mattlenton/GuruShots-auto-Voter/blob/master/GuruShitsAutoLike.js
> 
> I did a temp fix,
> Gurushots might change by tomorrow again

Thank you so much!

**Comment by mshonak** [comment]
I try the fix , still not working ( no error this time chromium browser just close after few second )

**Comment by mafiagr** [comment]
> I try the fix , still not working ( no error this time chromium browser just close after few second )

I had the same problem. Just run this again
npm install --save puppeteer

**Comment by mshonak** [comment]
Thanks , I will try to do so.

בתאריך יום ה׳, 24 בדצמ׳ 2020, 15:42, מאת vpanagopou ‏<
notifications@github.com>:

**Comment by noverotajs** [comment]
any hope on parmanent fix as this is called to be temporary?
Might this be becourse of christmas theme?

**Comment by xenbaloch** [comment]
It's still working for me. My Location: China, Connected using VPN (Japan)

**Comment by mshonak** [comment]
now it is working again ,  after i uninstall puppeteer and install it again , and use the fix . 
if it will stop working again I gass need to unmark // on the first line and mark // on the second one . 
thanks 
//const loginBtn = '#header > gs-header > div > div > a.signin';
   const loginBtn = 'header#JW7vAd.JW7vAe gs-header div > div > a.JW7vAg';

**Comment by xenbaloch** [comment]
Again not working I suppose!!!
